---
## Playbook for patching and restarting WebGate agents

- name: Patch webgate agents
  hosts: webgate_hosts
  ## Perform all tasks on 100% of the hosts in parallel
  serial: "100%"

  gather_facts: false

  become: yes
  become_user: "{{ privileged_user_webgate }}"
  become_method: sudo

  tasks:

    - block:

      - include_role:
          name: webgate_stop
        tags: [stop,restart]

      - include_role:
          name: restore_backup
        tags: restore_backup
        when: include_restore
      
      - include_role: 
          name: patch_webgate
        tags: patch_webgate
        when: include_webgate
    
      - include_role: 
          name: webgate_start
        tags: [start,restart]
