---
## Playbook for patching and restarting Oracle Fusion Middleware (WLS, OSB, SOA)

- name: Patch WebLogic servers including jdk and potentially OSB/SOA
  hosts: weblogic_hosts
  ## Perform all tasks on 25% of the hosts before going to the next 25%
  serial: "25%"

  gather_facts: False

  become: yes
  become_user: "{{ privileged_user }}"
  become_method: sudo

  tasks:

    - block:

      - include_role:
          name: wls_stop
        tags: [stop,restart]
      
      - include_role: 
          name: patch_java
        tags: patch_java
    
      - include_role: 
          name: patch_wls
        tags: patch_wls

      - include_role:
          name: patch_osb
        tags: patch_osb
        when: include_osb
  
      - include_role: 
          name: wls_start
        tags: [start,restart]
