---
## Tasks for patching webgate


##=====================================================
## Install java for opatch
##=====================================================

- block:

  - name: create dir for temporary java installation
    file:
      path: "{{ java_base }}"
      state: directory

  - name: fetch java tarball from artifactory
    include_role:
      name: common_prep_repo
    vars:
      repo_dir: java

  - name: get new java tarball
    find:
      paths: "{{ repo_install_dir }}"
      patterns: "*.tar*"
    register: tarball_to_install

  - name: install new java version
    unarchive:
      src: "{{ item.path }}"
      dest: "{{ java_base }}"
      remote_src: yes
    with_items:
      - "{{ tarball_to_install.files }}"

  - name: point symlink to new java version
    file:
      path: "{{ java_base }}/jdk"
      src: "{{ java_symlink }}"
      state: link

  - name: get old java tarball
    find:
      paths: "{{ repo_install_dir }}"
      patterns: "*.tar*"
    register: tarball_to_delete

  - name: clean up old java tarballs
    file:
      path: "{{ item.path }}"
      state: absent
    with_items:
      - "{{ tarball_to_delete.files }}"
    become: no

  when: not ansible_check_mode


##=====================================================
## Pre patch/rollback actions
##=====================================================

- name: get webgate patches applied
  command: "Opatch/opatch lsinv -jre {{ java_base }}/jdk -oh {{ webgate_home }}"
  args:
    chdir: "{{ wls_home }}"
  register: webgate_applied_pre
  changed_when: false
#  check_mode: no

- name: print webgate patches applied
  debug:
    var: webgate_applied_pre.stdout_lines

- name: create local lists dir if not present
  local_action:
    module: file
    state: directory
    mode: 0777
    path: "{{ lists_dir }}"
  become: no

- name: write webgate patches applied to local lists file
  local_action:
    module: blockinfile
    block: "{{ webgate_applied_pre.stdout_lines }}"
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - WEBGATE PATCH(ES) -->"
    create: yes
    mode: 0666
    path: "{{ lists_dir }}/{{ inventory_hostname }}"
  become: no

- block:

  - name: check if webgate_patch is provided
    assert:
      that:
        - webgate_patch | match ("^[a-zA-Z]*$")
      msg:
        - "webgate patch to install is not defined or not defined properly"
        - "please provide webgate_patch, f.e. --extra-vars webgate_patch='...'"

  - name: print webgate patch to be applied/removed (csv format)
    debug:
      msg: "webgate patch to apply/remove: {{ webgate_patch }}"

  when: not ansible_check_mode

- name: check if processes are absent (before patching)
  command: pgrep -f "httpd"
  register: ps_check
  changed_when: false
  failed_when: ps_check.rc == 0


##=====================================================
## Patch WebGate agent actions
##=====================================================

- block:

  - name: fetch webgate patch zipfile(s) from artifactory
    include_role:
      name: common_prep_repo
    vars:
      repo_dir: webgate

  - name: get patch zipfile(s) in repo
    find:
      paths: "{{ repo_install_dir }}"
      patterns: "*.zip*"
    register: webgate_patch_zipfiles

  - name: extract patch zipfile(s) to idk yet
    unarchive:
      src: "{{ item.path }}"
      dest: "{{ tmp_dir }}"
      list_files: yes
      remote_src: yes
    with_items:
      - "{{ webgate_patch_zipfiles.files }}"

  - name: apply webgate patch
    command: "Opatch/opatch lsinv -jre {{ java_base }}/jdk -oh {{ webgate_home }} -silent -force"
    args:
      chdir: "{{ wls_home }}"
    register: patch_result
    ## ignore (OoM) errors while patching was successful
#    failed_when: "'Result: Success' not in patch_result.stdout and 'Patch already installed' not in patch_result.stdout"

  - name: get webgate patch zipfile(s) in temp dir
    find:
      paths: "{{ repo_install_dir }}"
      patterns: "*.zip*"
    register: zipfiles_to_delete

  - name: clean up webgate patch zipfile(s) in temp dir
    file:
      path: "{{ item.path }}"
      state: absent
    with_items:
      - "{{ zipfiles_to_delete.files }}"
    become: no

  when: not rollback_webgate and not ansible_check_mode

 
##=====================================================
## Rollback actions
##=====================================================

- block:

  - name: rollback webgate patch
    command: "Opatch/opatch lsinv -jre {{ java_base }}/jdk -oh {{ webgate_home }} -silent"
    args:
      chdir: "{{ wls_home }}"

  - name: apply different (previous) webgate patch if provided
    command: "Opatch/opatch lsinv -jre {{ java_base }}/jdk -oh {{ webgate_home }} -silent -force"
    args:
      chdir: "{{ wls_home }}"
    register: patch_result
    ## ignore (OoM) errors while patching was successful
#    failed_when: "'Result: Success' not in patch_result.stdout and 'Patch already installed' not in patch_result.stdout"
    when: rollback_webgate_to_patch != ""

  when: rollback_webgate

##=====================================================
## Post patch/rollback actions
##=====================================================
 
- name: get webgate patches applied
  command: "Opatch/opatch lsinv -jre {{ java_base }}/jdk -oh {{ webgate_home }}"
  args:
    chdir: "{{ wls_home }}"
  register: wls_applied_post
  changed_when: false
  check_mode: no

- name: print webgate patches applied
  debug:
    var: webgate_applied_post.stdout_lines

- name: write webgate patches applied to local lists file
  local_action:
    module: blockinfile
    block: "{{ webgate_applied_post.stdout_lines }}"
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK - WEBGATE PATCH(ES) -->"
    create: yes
    mode: 0666
    path: "{{ lists_dir }}/{{ inventory_hostname }}"
  become: no

- name: clean up temporary java installation
  file:
    path: "{{ java_base }}"
    state: absent
