---

- name: create remote repo file directory
  file:
    path: "{{ repo_install_dir }}"
    state: directory
    owner: "{{ privileged_user }}"
    group: "{{ privileged_group }}"
    mode: 0777

- name: push file to target
  copy: 
    src: "/repos/{{ repo_source }}/{{ repo_dir }}/{{ item }}"
    dest: "{{ repo_install_dir }}"
    mode: 0644
  become: no
  with_items:
    - "{{ artifacts }}"
